diccionario = {
    12 :["utilizar mas placas de las permitidas.", "$50"],
    26 :["no portar llanta de repuesto en vehiculo.", "$50"],
    34 :["no encender las luces direccionales al cruzar o cambiar de carril.", "$50"],
    64 :["bajar o subir pasajeros en lugares no permitidos o esquinas.", "$100"],
    69 :["conducir motocicleta sin el casco protector.", "$100"],
    86 :["conducir con licencia falsicicada o suplantar al propietario de la licencia.", "$150"],
    106 :["circular con las luces apagadas en horas nocturnas.", "$150"],
    75 :["no respetar los dispositivos de seguridad colocados en la zona de control temporal de trafico por la autoridad de transito y por los gestores y por los gestores de trafico.", "$100"],
    23 :["condicur con la luz alta en la ciudad.", "$50"],
    28 :["carecer parcialmente de luz delantera o trasera.", "$50"],
    115 :["negarse a la realizacion de pruebas que se establezcan para la deteccion de posibles intoxicaciones por alcohol, drogas, estimulantes o esupefacientes y otras sustancias analogas.", "$150"],
    76 :["alterar las condiicones tecnicas de toda clases de vehiculos y motocicletas asi como: colocar bazucas, oculaquier tipo de dispositivo que pueda generar contaminacion visual o auditiva.", "$100"],
    70 :["detenerse sobra las zonas d eseguridad peatonal.", "$100"],
    112 :["conducir vehiculos con el sistema de freno en mal estado.", "$150"],
    118 :["conducir manipulando o haciendo uso del telefono celular, radio de comunicacion, agenda de cualquier clase, dispositivo o aparato electronico, asi como irlo sosteniendo en las manos, dedos o llevando entre los brazos o sobre las piernas a otra persona, animales o cualquier otro objeto o cosa, que dificulte el manejo, limite de visibilida y ocacione o posibilite la distraccion en el conductor.", "$150"],
    87 :["transportar poersonas en funcion comercial, sin el permiso correspondiente.", "$150"],
    14 :["circular con vehiculos con placas nacinales, fuera de la jornada laboral, si la debida autorizacion.", "$50"],
    125 :["circular con vvehiculos automotores idesel, que contengan como impureza azufres que sobrepase el limite estandar permisible por las normas dictadas por autoriadd competente.", "$150"],
    109 :["no respetar la señal de alto o de ceder el paso.", "$150"],
    84 :["sobrepasar a alta velocidad un microbus, un bus o microbus escolar cuano est estacionado subiendo o bajando alumnos.", "$150"],
    51 :["transladar cadaveres sin autorizacion de la autoridad competente.", "$100"],
    123 :["circular motocicletas sin cascos certificados.", "$150"],
    101 :["estacionarse en zona de carga, en horas restringidas.", "$150"],
    62 :["carecer de luz de freno.", "$100"],
    83 :["abandonar el vehiculo por desperfectos mecanicos, en las vias publicas, por mas de 24 horas.", "$150"],
    4 :["no portar targeta de circulacion.", "$50"],
    85 :["circular en horarios y lugares no permitidos por medido de resolucion emitidda por las direcciones generales dde transito, dde transporte o de transporte de carga del viceministerio de transporte.", "$150"],
    44 :["no atender la indicacion realiza por la autoridad que se encuentre gestionando el trafico en las vias.", "$100"],
    107 :["circular en la ciudad o carreteras con vehicuos que tengan instaladas barras led.", "$150"],
    108 :["conducir con el motor desconectado.", "$150"],
    20 :["circular con el vehiculo con escape libre, bazuca o aditamento que prodduzca estridencia que sobre pase llimites legalmente admisibles.", "$50"],
    79 :["circular a mayor velocidad de la reglamentaria.", "$150"],
    80 :["disputarse la via con otro vehiculo.", "$150"],
    127 :["pintar sobre la red vial sin previa autorizacion; asi como dañar, remover o inutilizar las señales viales.", "$150"],
    52 :["estacionarse formato doble via.", "$100"],
    61 :["carecer de espejo retrovisor y espejos laterales izquierdo y derecho.", "$100"],
    11 :["no llevar las placas en un lugar visible.", "$50"],
    9 :["circular con una placa.", "$50"],
    66 :["girar a la izquierda donde no es permitido.", "$100"],
    5 :["conducir vehiculo como instructor de una escuela de manejo sin su respectivvo carnet o portarlo vencido.", "$50"],
    43 :["rebasar o cruzar la doble linea amarilla central que divide la via doble en el sentido de circulacion.", "$100"],
    102 :["estacionarse en zona de seguridad señalizada.", "$150"],
    56 :["no conceder el paso a peatones que caminen en zona de seguridad o cuando se encuentre en peligro.", "$100"],
    114 :["conducir los vehiculos bajo los efectos de bebidas embriagantes, estupefacientes o enervantes.", "$150"],
    120 :["conducir en motocicletas por ciclovias y carriles destinados para la circulacion de becicletas.", "$150"],
    98 :["conducir estando cancelada la licencia.", "$150"],
    46 :["circular con placas de vendedor de vehiculos cuando no estan en venta.", "$100"],
    13 :["no portar licencia de conducir.", "$50"],
    49 :["negarse a presentar los dicumentos de transito a la autoriddad competente.", "$100"],
    59 :["no respetar las señales de precaucion.", "$100"],
    31 :["llevar anuncios en las ventanillas o parabrisas que afecten la visibilidad del conductor.", "$50"],
    71 :["no cender el paso a los peatones que se encuentran cruzano por la via de seguridad peatonal.", "$100"],
    78 :["conucir en sentido contrario, salvo cuando sobrepase a otros vehiculos en las zonas y momentos permitidos.", "$150"],
    130 :["facilitar o prestar placa o placas del vehiculo para que las utilize otro.", "$150"],
    47 :["circular vehiculos con placas extrangeras sin el permiso correspondiente o despues del tiempo reglamentario.", "$100"],
    57 :["llevar pasajeros a la izquierda del conductor.", "$100"],
    35 :["conducir describiendo curvas o haciendddo 'zig zag'.", "$100"],
    24 :["conducir sin el destintivo rojo durante el dia cuanod la carga sobresale de la carroseria en la parte trasera, y por la noche sin una señal reflectiva.", "$50"],
    16 :["cicular con vehiculos fuera del sistema del registro publico de vehiculos por falta de refrenda.", "$50"],
    110 :["no respetar la luz froja del semaforo.", "$150"],
    1 :["virar en 'U' donde no es permitido.", "$50"],
    74 :["sujetarse a otro vehiculo en marcha mientras se conduce una bicicleta o motocicleta.", "$100"],
    2 :["subrepasar a otro vehiculo sin antes indicar la maniobra.", "$50"],
    117 :["remover el sistema de control de emisiones.", "$150"],
    104 :["estacionarse frente a entradas pricipales de edificios publicos, teatros, hoteles, bancos, hospitales y recidencias particulares obstaculizando el acceso a ellos.", "$150"],
    60 :["no dar luz baja al encontrarse otro vehiculo en sentio opuesto.", "$100"],
    111 :["sobrepasar a otro vehiculo cuando otro venga en direccion opuesta, icha maniobra cause peligro.", "$150"],
    48 :["circular con vehiculos no inscritos en el registro publico de vehiculos.", "$100"],
    65 :["conducir vehiculos con exceso de cargar a su capacida o carga voluminosa mal acondicionada.", "$100"],
    25 :["conducir sin el banderin y/o dispositivo de aprendizaje. en esto caso el responsable es el instrutor.", "$50"],
    93 :["intentar sobornar a las autoridades del cotral vial.", "$150"],
    128 :["instalar señales o sirenas rotativas voluminosas en vehiculos no autorizdos.", "$150"],
    17 :["estacionarse a mas de 30cm de la cuneta.", "$50"],
    95 :["circular en el carril izquierdo de la via sin ir sobrepasando.", "$150"],
    39 :["no disminuir la velocidad en zonas restringidas tales como: colegios, esculas, hospitales, centros deportivos y mercados.", "$100"],
    119 :["conducir motocicletas sin utilizar anteojos protectores cuando el casco no tenga protector cortaviento.", "$150"],
    50 :["trasladar cadaveres sin autorizacion de la autoridad competente.", "$100"],
    30 :["usar halogenos en la ciudad a una altura superior a los 75cm desde el suelo.", "$50"],
    40 :["sobrepasar a otro vehiculo en boca calle.", "$100"],
    94 :["conducir vehiculos, cuatrimotos, motociletas, tricimotos y cuadriciclos en las playas y sition no autorizados.", "$150"],
    91 :["no conducir con alguna de las series identificativas de VIN, chasis grabados y motor en las que constan en la tarjeta de circulacion.", "$150"],
    132 :["circular con el sistema de control de emiciones en mal estado de funcionamiento.", "$150"],
    36 :["estacionarse en area señalizada exclucivamente para vehiculos de transporte de personas con discapacidadd que porten placa o distintivo extendido por la autoridad competente y los lugares reservados para el estacionamiento vvehiculos conducidos por las mujeres embarazadas.", "$100"],
    58 :["conducir vehiculos con niños menores de 3 años de edad, sin que se encuentre con una silla infantil debidamente sujetada por cinturones de seguridad y/o ser transportando en la cabina del vehiculo en sentio opuesto.", "$100"],
    116 :["no respetar o atender señales del personal autorizado que se encuentre realizando trabajos en la via publica.", "$150"],
    97 :["conducir estando suspendida la licencia.", "$150"],
    68 :["permitir el conductor de un vehiculo automotor que su acompañante en el asiento delantero, viaje sin utilizar el cituron de seguriddad.", "$100"],
    33 :["inclumplir las dispociciones relativas al percentaje minimo de paso de luz solar en los vidrios polarizados regulados en esta ley.", "$50"],
    38 :["no respetar fila cuando haya congestionamiento de vehiculos o penetrar con el vehiculo en una interseccion o en el paso , si la situacion de la circulacion estal que, previsiblemente puede quedar detenido en forma que impide u obstruya la ciruclacion trasversal.", "$100"],
    89 :["circular sin placas o con placas que no correspondan a la emision vigente.", "$150"],
    21 :["osbtruir por completo el paso en las vias publicas con entierros, desfile y eventos deportivos.", "$50"],
    81 :["sobrepasar a otro vehiculo en curvas, puentes, trechos angostos o aproximaciones a ellos.", "$150"],
    92 :["no coincidir las caracteristicas fisicas del vehiculo con la q2ue costan en la targeta dde circulacion.", "$150"],
    113 :["utilizar la via publica para competencias automovilistico.", "$150"],
    41 :["colocarse en el carril que no le corresponde en la boca-calle para iniciar la marcha.", "$100"],
    15 :["no inscriir en el registro pubnlico de vehiculos lso documento de propiedad, transferencia o tendencia legitima del vehiculo en el termino que la ley etablece.", "$50"],
    67 :["no utilizar el conductor el cinturon de seguridad.", "$100"],
    72 :["no ceder el paso a cilcistas que transiten por la via publica.", "$100"],
    121 :["circular en motocilcetas por el hombre de caller o en el bordillo del carril izquierdo o en las lineas divisoras de los carriles.", "$150"],
    82 :["no respetar el carril reglamentario al virar a la izquierda.", "$150"],
    73 :["no respetar a la zona de la via publica destinada para la circulacion de la bicicletas.", "$100"],
    29 :["no portar triangulos reflectivos o dispositivos preventios de seguridad.", "$50"],
    88 :["conducir vehiculos con placas que pertenecen a otro.", "$150"],
    19 :["estacionar frente a cochera que no le corresponda.", "$50"],
    54 :["no mover un vehiculo u objeto que obstruya el libre transito producto de un siniestro vial , siempre que solo existan daños materiales y/o daños personales leves.", "$100"],
    18 :["estacionarse al contrario de la circulacion de la via.", "$50"],
    6 :["ciruclar con tarjeta de circulacion vencida.", "$50"],
    42 :["aumentar la velocidad cuando otro vehiculo trate de sobrepasar.", "$100"],
    27 :["circular con llantas lisas o en mal estaddo.", "$50"],
    96 :["conucir sin estar autorizado para ello.", "$150"],
    45 :["conducir con licencia inadecuada al tipo de vehiculo.", "$100"],
    99 :["estacionarse en zona prohibida o eje preferencial.", "$150"],
    131 :["sobrepasar el limite de emisiones de gases permitido.", "$150"],
    8 :["conducir con licencia vencidda.", "$50"],
    126 :["retirarse el involucrado del lugar del accidente.", "$150"],
    22 :["obstruir por completo el paso en las vias publicas con entierros, desfile y eventos deportivos.", "$50"],
    103 :["estacionarse en la acera, paralelo a la via o atravesado.", "$150"],
    7 :["circular con licencia extrangera fuera del tiempo reglamentario.", "$50"],
    3 :["circular con placas no visibles.", "$50"],
    63 :["ocasionar accidentes por desperfectos mecanicos.", "$100"],
    37 :["no ceder el paso a vehiculos de emergencia, cuando tienen activadas las sirenas y señales rotativvas luminosas.", "$100"],
    55 :["ignorar la indicacion de una autoridad competente de mover su vehiculo u otro objeto que se encuenre obstruyendddo l avia publica y el libre transito, producto de un siniestro vial con daños materiales y/o personales o por otras razones que la autoridad estime competente.", "$100"],
    100 :["estacionar en paradas de buses.", "$150"],
    10 :["carecer de luz de placa.", "$50"],
    32 :["tirar basura de los vehiculos.", "$50"],
    105 :["efectuar reparaciones en la via publica de manera permanente.", "$150"],
    90 :["circular con placas falsificadas.", "$150"],
    53 :["no respetar el derecho de via o intersectar la via.", "$100"],
    122 :["circular despues delas 18 horas y antes de las 6 horas del dia siguiente, sin que el motociclea y/o su acompañante usen chalecos o chaquetas reflectantes visibles.", "$150"],
    129 :["modificar sin autorizacion los motores, para aumentar su capacidad de velocidad, sin fines deportivos.", "$150"],
    124 :["ciruclar, por las visa terrestres del pais, con vehiculos automotores que utilizen y contengan mas de trece milesimas de gramo de plomo por litro de combustible con aditivo.", "$150"],
    77 :["retroceder o efectuar maniobras de mucho transito.", "$150"]
}

